export const mechanismSpecs = [
  {
    id: 'sn2',
    label: 'SN2',
    title: 'SN2 substitution',
    short: 'Backside attack and inversion',
    question: 'How can one elementary step form a bond, break a bond, and invert a stereocentre?',
    summary: 'Scrub through a hydroxide SN2 substitution and connect electron movement, geometry, and activation energy.',
    evidence: 'Idealized SN2 reaction coordinate - geometry and energy are teaching models, not a quantum calculation.',
    control: ['Reactants', 'Products'],
    legend: ['electron pair', 'forming C-O bond', 'breaking C-Cl bond', 'single energy barrier'],
    swatches: ['#e0ad35', '#69736f', '#67a85f', '#a57a31'],
    parts: {
      Nucleophile: 'An electron-pair donor that approaches the carbon from the side opposite the leaving group.',
      Electrophile: 'The carbon atom accepting an electron pair as the new bond forms.',
      'Leaving group': 'The atom or group departing with the shared electron pair from the breaking bond.',
      'Transition state': 'A fleeting maximum-energy arrangement with partial bonds to both incoming and leaving groups.',
    },
    steps: [
      ['Backside approach', 'The nucleophile approaches opposite the leaving group, aligning its electron pair with the C-X antibonding orbital.'],
      ['One concerted event', 'Bond formation and bond breaking occur together. There is no stable intermediate in an elementary SN2 step.'],
      ['The energy barrier', 'The transition state is less stable than reactants or products, producing the activation-energy maximum.'],
      ['Configuration inverts', 'The three substituents turn through the carbon centre like an umbrella, giving inversion of stereochemistry.'],
    ],
    check: { q: 'At the energy maximum, what must the bond display show?', options: ['Only a complete C-O bond', 'A stable carbocation between two separate steps', 'Partial C-O formation and partial C-Cl cleavage at the same time'], answer: 2, explanation: 'The synchronized midpoint shows the concerted transition state rather than a stable intermediate.' },
    guidedViews: [
      { progress: .05, part: 'Nucleophile' },
      { progress: .48, part: 'Transition state' },
      { progress: .5, part: 'Transition state' },
      { progress: .92, part: 'Leaving group' },
    ],
    observationPrompts: [
      'Check the nucleophile and leaving group before scrubbing.',
      'Pause near the maximum and inspect both curved electron arrows.',
      'Compare the partial bonds with the energy marker.',
      'Follow H, D and CH3 as the tetrahedral center inverts.',
    ],
    playMs: 4200,
  },
  {
    id: 'suzuki',
    label: 'Suzuki',
    title: 'Suzuki C-C coupling',
    short: 'Pd carries two aryl groups',
    question: 'How can a palladium catalyst connect two carbon fragments without being consumed?',
    summary: 'Follow an idealized Suzuki-Miyaura sequence from aryl bromide and arylboronic acid through an oblique Pd(II) square plane to a twisted biaryl product.',
    evidence: 'Idealized Pd catalytic sequence - oxidative addition, aryl transfer, and reductive elimination are shown as formal teaching states. The Pd(II) square plane and aryl torsions are geometric teaching guides, not a calculated electronic structure. Ligand identity, active Pd species, and rate-limiting step depend on conditions.',
    control: ['Reactants', 'Biaryl product'],
    legend: ['aromatic aryl ring', 'Pd catalyst', 'square-planar Pd(II) guide', 'forming C-C bond'],
    swatches: ['#45504d', '#b9c0bf', '#8aa5a8', '#d4ae45'],
    parts: {
      'Aryl bromide': 'One carbon fragment enters the cycle through a C-Br bond. The display uses a generic aryl bromide rather than claiming one substrate or ligand set.',
      'Arylboronic acid': 'The second aryl fragment starts as Ar-B(OH)2. Base activation and the detailed boronate exchange network are condensed into the aryl-transfer teaching state.',
      'Palladium catalyst': 'Palladium changes coordination and formal oxidation state through the cycle. Formal Pd(0)/Pd(II) labels are bookkeeping, not literal point charges on the atom.',
      'cis-diaryl Pd': 'A teaching representation of the Pd(II) intermediate after aryl transfer. The four donors occupy one square plane, while the aryl ring planes are torsioned about their Pd-C bonds so they can be inspected separately.',
      'Biaryl product': 'The new C-C bond joins the two aryl fragments. The rings are drawn twisted about that bond, not as an artificially flat biphenyl. Palladium is regenerated and is not part of the product.',
    },
    steps: [
      ['Start with both aryl partners', 'The generic aryl bromide and arylboronic acid are shown alongside a formal Pd(0) catalyst state. The next step opens the C-Br bond rather than making a direct C-C jump.'],
      ['Oxidative addition opens C-Br', 'A Pd centre interacts with the aryl C-Br bond. The model condenses ligand details into an idealized formal oxidative-addition state with Pd-C and Pd-Br bonds in an oblique square plane.'],
      ['Aryl transfer builds cis-diaryl Pd', 'A base-activated boronate can transfer its aryl fragment to palladium. Inspect the two cis Pd-C bonds, the two L donors, and the distinct torsion of each aryl ring about its Pd-C bond.'],
      ['Reductive elimination makes C-C', 'The C-C bond forms as the biaryl product leaves with a visible ring twist, while a formal Pd(0) catalyst state is regenerated. The catalyst mediates the pathway but is not consumed.'],
    ],
    check: { q: 'Which observation identifies palladium as a catalyst in this teaching cycle?', options: ['Bromine remains attached to the aryl product', 'A Pd-bound intermediate gives a biaryl product and a regenerated Pd state', 'The two aryl rings begin on opposite sides of the view'], answer: 1, explanation: 'The display follows the carbon fragments into the biaryl product while palladium returns to a state available for another cycle.' },
    guidedViews: [
      { progress: .04, part: 'Aryl bromide' },
      { progress: .36, part: 'Palladium catalyst' },
      { progress: .62, part: 'cis-diaryl Pd' },
      { progress: .96, part: 'Biaryl product' },
    ],
    observationPrompts: [
      'Locate the aryl C-Br and aryl-B bonds before palladium engages either fragment.',
      'Follow the C-Br bond as Pd-C and Pd-Br bonds appear.',
      'Inspect the two cis Pd-C bonds and the two L donors in the oblique square plane after bromide has left.',
      'Check that the biaryl leaves with a ring twist while the Pd centre returns as a separate catalyst state.',
    ],
    playMs: 7600,
  },
  {
    id: 'dielsAlder',
    label: '[4+2]',
    title: 'Diels-Alder [4+2]',
    short: 'Orbital phase makes a ring',
    question: 'Why can a diene and dienophile form two C-C bonds in one thermal step?',
    summary: 'Align butadiene and ethene, inspect a qualitative frontier-orbital phase model, then follow a concerted [4+2] cycloaddition to cyclohexene.',
    evidence: 'Idealized thermal Diels-Alder symmetry archetype - phase-coloured lobe coefficients are a qualitative LCAO model, not calculated electron trajectories, charge clouds, or molecular-orbital isosurfaces. Unactivated butadiene plus ethene is shown for symmetry, not as a routine room-temperature reaction.',
    control: ['Separated pi systems', 'Cyclohexene product'],
    legend: ['diene pi system', 'dienophile pi system', 'wavefunction phase', 'forming C-C sigma bonds'],
    swatches: ['#45504d', '#69736f', 'linear-gradient(90deg, #d37742 0 50%, #456ba4 50% 100%)', '#d4ae45'],
    parts: {
      'Diene HOMO': 'Qualitative phase-coloured p-lobes trace the pi framework of the s-cis diene. The terminal faces that meet the dienophile are enlarged, but the model is not a calculated orbital surface.',
      'Dienophile LUMO': 'Qualitative phase-coloured p-lobes represent ethene pi-star. Matching phase at both approaching terminal contacts allows constructive overlap in this thermal [4+2] teaching case.',
      'Transition state': 'A concerted cyclic arrangement with two partial C-C bonds. This model has no carbocation or zwitterionic intermediate.',
      Cycloadduct: 'Cyclohexene formed after two new sigma bonds appear and the pi bonds reorganize. Stereochemical outcomes depend on the starting geometry.',
    },
    steps: [
      ['Set the reactive diene geometry', 'Butadiene must adopt an s-cis arrangement that brings its terminal carbons to the same face of the dienophile.'],
      ['Match HOMO and LUMO phase', 'The phase-coloured terminal lobes show a qualitative constructive overlap at both forming contacts. Colour marks wavefunction sign, not charge.'],
      ['Cross one concerted barrier', 'Two C-C sigma bonds form in the same pericyclic event while the pi system reorganizes. Bond formation can be asynchronous in real substituted cases, but there is no ionic intermediate in this idealized pathway.'],
      ['Read the cyclohexene product', 'The product contains a new six-membered ring and one remaining pi bond. Concerted Diels-Alder reactions can be stereospecific; this unsubstituted model does not encode a particular stereochemical outcome.'],
    ],
    check: { q: 'What should the transition-state display show for this idealized thermal Diels-Alder reaction?', options: ['A carbocation after only one new C-C bond', 'Two partial C-C bonds in one cyclic arrangement', 'A complete product ring before the dienophile approaches'], answer: 1, explanation: 'The [4+2] display represents one concerted pericyclic step: both new sigma bonds are forming as the pi system reorganizes.' },
    guidedViews: [
      { progress: .26, part: 'Diene HOMO' },
      { progress: .42, part: 'Dienophile LUMO' },
      { progress: .65, part: 'Transition state' },
      { progress: .96, part: 'Cycloadduct' },
    ],
    observationPrompts: [
      'Find the two terminal diene carbons that will make the new sigma bonds.',
      'Compare the orange and blue terminal lobes across both approaching contacts.',
      'Pause in the cyclic transition arrangement and count two partial C-C bonds.',
      'Trace the same six carbon atoms into the cyclohexene ring and its remaining pi bond.',
    ],
    playMs: 5600,
  },
  {
    id: 'e2',
    label: 'E2',
    title: 'E2 elimination',
    short: 'Base, anti-periplanar, one step',
    question: 'How can a base remove a proton and expel a leaving group in one concerted step?',
    summary: 'Scrub through an E2 elimination: a base removes a beta-hydrogen as the leaving group departs anti to it and a C=C pi bond forms.',
    evidence: 'Idealized E2 reaction coordinate - geometry and energy are teaching models, not a quantum calculation. Anti-periplanar alignment of the beta-H and leaving group is shown as the reactive arrangement.',
    control: ['Reactants', 'Alkene product'],
    legend: ['base electron pair', 'forming C=C pi bond', 'breaking C-H and C-Br bonds', 'single energy barrier'],
    swatches: ['#e0ad35', '#67a85f', '#69736f', '#a57a31'],
    parts: {
      Nucleophile: 'The base. Its lone pair removes the beta-hydrogen; in E2 the base acts as a Bronsted base rather than attacking carbon.',
      Electrophile: 'The two carbons of the substrate. The beta-carbon loses a hydrogen and the alpha-carbon loses the leaving group as a C=C double bond forms between them.',
      'Leaving group': 'The group that departs with the C-X bonding pair, anti-periplanar to the removed beta-hydrogen.',
      'Transition state': 'A single concerted arrangement: the C-H and C-X bonds break while the C=C pi bond forms. There is no carbocation intermediate.',
    },
    steps: [
      ['Anti-periplanar set-up', 'The base approaches a beta-hydrogen that sits anti-periplanar to the leaving group - the hydrogen and the leaving group point to opposite sides of the C-C bond.'],
      ['One concerted step', 'The base removes the beta-hydrogen while the leaving group departs and the C=C pi bond forms, all in the same elementary step. No carbocation forms.'],
      ['The energy barrier', 'Bond-breaking and bond-making happen together through a single transition state, so E2 shows one activation barrier and its rate depends on both substrate and base.'],
      ['Read the alkene product', 'The result is an alkene, the protonated base, and the leaving group as an anion. Compare this with SN2: same reactants, but the base attacks hydrogen instead of carbon.'],
    ],
    check: { q: 'What must the E2 transition-state display show?', options: ['A planar carbocation after the leaving group departs', 'The C-H and C-X bonds breaking as the C=C bond forms in one step', 'The base bonding to the carbon that holds the leaving group'], answer: 1, explanation: 'E2 is concerted: proton removal, leaving-group loss, and pi-bond formation occur together through one transition state.' },
    guidedViews: [
      { progress: .05, part: 'Nucleophile' },
      { progress: .5, part: 'Transition state' },
      { progress: .52, part: 'Transition state' },
      { progress: .95, part: 'Leaving group' },
    ],
    observationPrompts: [
      'Note that the beta-hydrogen and the leaving group point to opposite sides before scrubbing.',
      'Pause near the middle and follow all three curved arrows at once.',
      'Watch the C=C pi bond appear as the two old bonds fade.',
      'Confirm the products: an alkene, the protonated base, and the leaving anion.',
    ],
    readout: (p) => [
      ['Step type', 'concerted (one step)'],
      ['Bonds changing', p < .5 ? 'C-H and C-Br weakening' : 'C=C forming; Br- leaving'],
      ['Geometry', 'anti-periplanar H and leaving group'],
      ['Product', p < .6 ? 'alkene not yet formed' : 'alkene + Br- + protonated base'],
    ],
    playMs: 4600,
  },
  {
    id: 'sn1',
    label: 'SN1',
    title: 'SN1 substitution',
    short: 'Carbocation, then capture',
    question: 'Why does a stepwise substitution go through a planar carbocation and give racemization?',
    summary: 'Follow a stepwise SN1: the leaving group ionizes first to a planar carbocation, then a nucleophile is captured from either face.',
    evidence: 'Idealized SN1 reaction coordinate - geometry and energy are teaching models, not a quantum calculation. A tertiary substrate is shown so the carbocation is the sort that would realistically form.',
    control: ['Reactants', 'Product'],
    legend: ['electron pair', 'forming C-Nu bond', 'breaking C-Br bond', 'two barriers + intermediate well'],
    swatches: ['#e0ad35', '#67a85f', '#69736f', '#a57a31'],
    parts: {
      Electrophile: 'The central carbon. It starts tetrahedral, flattens to a trigonal planar carbocation when the leaving group departs, then becomes tetrahedral again after capture.',
      Nucleophile: 'An electron-pair donor that captures the carbocation. Because the cation is flat, it can be attacked from either face.',
      'Leaving group': 'The group that leaves first, on its own, in the slow rate-determining ionization step.',
      'Transition state': 'This mechanism has two transition states and a genuine carbocation intermediate between them - shown as a well in the energy profile.',
    },
    steps: [
      ['Ionization comes first', 'The C-Br bond breaks on its own, without help from the nucleophile. This slow, rate-determining step is the tall first barrier.'],
      ['A planar carbocation', 'The carbon left behind is a flat, trigonal planar carbocation. This intermediate sits in a well in the energy profile - higher than the reactant but between two barriers.'],
      ['Capture from either face', 'The nucleophile adds to the flat cation. Because both faces are open, a single stereocentre would be attacked from both sides, giving racemization.'],
      ['Two barriers, one intermediate', 'Unlike SN2, SN1 is stepwise: an energy well separates ionization from capture. The rate depends only on the substrate, not the nucleophile.'],
    ],
    check: { q: 'What distinguishes the SN1 energy profile from SN2?', options: ['SN1 has a single concerted barrier', 'SN1 has two barriers with a carbocation intermediate in a well between them', 'SN1 has no transition state at all'], answer: 1, explanation: 'SN1 is stepwise: a real carbocation intermediate sits in an energy well between the ionization and capture transition states.' },
    guidedViews: [
      { progress: .08, part: 'Leaving group' },
      { progress: .5, part: 'Electrophile' },
      { progress: .5, part: 'Nucleophile' },
      { progress: .95, part: 'Nucleophile' },
    ],
    observationPrompts: [
      'Watch the C-Br bond break before the nucleophile does anything.',
      'Pause at the middle: the carbon is flat and sits in the energy well.',
      'See the nucleophile approach the open face of the flat cation.',
      'Compare the two-barrier profile with the single SN2 barrier.',
    ],
    readout: (p) => [
      ['Step type', 'stepwise (two steps)'],
      ['Rate-determining', 'C-Br ionization'],
      ['Intermediate', p < .4 ? 'not yet formed' : p < .62 ? 'planar carbocation' : 'consumed'],
      ['Stereochemistry', 'either face -> racemization'],
    ],
    playMs: 6400,
  },
  {
    id: 'carbonyl',
    label: 'C=O add',
    title: 'Nucleophilic addition to C=O',
    short: 'Trigonal planar to tetrahedral',
    question: 'How does a nucleophile add to a carbonyl and turn a flat carbon into a tetrahedral one?',
    summary: 'Watch a nucleophile add to a carbonyl carbon: the C=O pi bond breaks onto oxygen (an alkoxide) as the carbon rehybridizes from trigonal planar to tetrahedral.',
    evidence: 'Idealized 1,2-addition reaction coordinate - geometry and energy are teaching models, not a quantum calculation. A generic anionic nucleophile and an aldehyde are shown.',
    control: ['Reactants', 'Alkoxide product'],
    legend: ['nucleophile electron pair', 'forming C-Nu bond', 'C=O reorganizing to C-O(-)', 'single energy barrier'],
    swatches: ['#e0ad35', '#67a85f', '#45504d', '#a57a31'],
    parts: {
      Electrophile: 'The carbonyl carbon. It is electron-poor because oxygen pulls electron density from the C=O bond, and it goes from trigonal planar (sp2) to tetrahedral (sp3).',
      Nucleophile: 'An electron-pair donor that attacks the carbonyl carbon, approaching slightly off the C=O axis (the Burgi-Dunitz angle).',
      'Transition state': 'The C=O pi bond breaks as the C-Nu bond forms; the two pi electrons move onto oxygen, which becomes a negatively charged alkoxide. One barrier.',
    },
    steps: [
      ['A polarised carbonyl', 'The C=O bond is polarised: oxygen is electron-rich, the carbon electron-poor. That makes the carbon the site a nucleophile attacks - directly, at the carbonyl carbon (1,2-addition).'],
      ['The nucleophile adds', 'As the nucleophile forms a bond to carbon, the C=O pi bond breaks and both of its electrons move onto oxygen.'],
      ['Trigonal planar to tetrahedral', 'The carbon started flat with three groups; after addition it has four groups and is tetrahedral. Oxygen is now a negatively charged alkoxide.'],
      ['One step to the alkoxide', 'A single barrier leads to the alkoxide, which a later proton source turns into an alcohol. Contrast this direct 1,2-addition with Michael (1,4) addition.'],
    ],
    check: { q: 'What happens to the carbonyl carbon during 1,2-addition?', options: ['It stays trigonal planar throughout', 'It goes from trigonal planar to tetrahedral as the C=O pi bond moves onto oxygen', 'It gains a positive charge and loses a group'], answer: 1, explanation: 'The nucleophile adds to the carbon and the pi electrons move to oxygen, so the carbon rehybridizes sp2 -> sp3 and oxygen becomes an alkoxide.' },
    guidedViews: [
      { progress: .05, part: 'Nucleophile' },
      { progress: .45, part: 'Transition state' },
      { progress: .6, part: 'Electrophile' },
      { progress: .95, part: 'Transition state' },
    ],
    observationPrompts: [
      'Note the electron-poor carbonyl carbon before the nucleophile approaches.',
      'Follow both curved arrows: Nu onto carbon, pi onto oxygen.',
      'Watch the carbon pyramidalize from flat to tetrahedral.',
      'Confirm oxygen carries the negative charge as an alkoxide.',
    ],
    readout: (p) => [
      ['Reaction type', '1,2-addition to C=O'],
      ['Carbon geometry', p < .5 ? 'trigonal planar (sp2)' : 'tetrahedral (sp3)'],
      ['C=O bond', p < .5 ? 'double bond' : 'single; O is alkoxide'],
      ['Product', p < .6 ? 'no addition yet' : 'alkoxide (-> alcohol)'],
    ],
    playMs: 4600,
  },
  {
    id: 'michael',
    label: '1,4-add',
    title: 'Michael 1,4-addition',
    short: 'Conjugate addition to an enone',
    question: 'Why does a nucleophile add to the far beta-carbon of an enone instead of the carbonyl?',
    summary: 'Follow a Michael (conjugate) addition: a nucleophile adds to the beta-carbon of an enone, electrons relay through the conjugated system to oxygen, and the enolate is protonated.',
    evidence: 'Idealized 1,4-addition reaction coordinate - geometry and energy are teaching models, not a quantum calculation. A generic soft nucleophile and an enone are shown; the enolate is drawn as one resonance form.',
    control: ['Reactants', '1,4-product'],
    legend: ['nucleophile electron pair', 'forming C-Nu and C-H bonds', 'conjugated pi system reorganizing', 'single addition barrier'],
    swatches: ['#e0ad35', '#67a85f', '#45504d', '#a57a31'],
    parts: {
      Electrophile: 'The enone (Michael acceptor). Conjugation makes the far beta-carbon electron-poor, so the nucleophile adds there rather than at the carbonyl carbon.',
      Nucleophile: 'An electron-pair donor (a soft nucleophile) that adds to the beta-carbon in a 1,4 sense.',
      'Transition state': 'Adding at the beta-carbon relays electrons through the C=C and C=O system onto oxygen, giving an enolate; a proton then caps the alpha-carbon to give the product.',
    },
    steps: [
      ['A conjugated acceptor', 'In an enone the C=C and C=O are conjugated. This spreads the electron-poor character onto the far beta-carbon - the carbon two positions from oxygen.'],
      ['Add to the beta-carbon', 'The nucleophile adds to the beta-carbon (1,4-addition), not the carbonyl carbon (which would be 1,2). This is the defining choice of a Michael addition.'],
      ['Electrons relay to oxygen', 'The C=C pi electrons shift toward the carbonyl and the C=O pi electrons move onto oxygen, giving a resonance-stabilised enolate.'],
      ['Protonate to the product', 'A proton caps the alpha-carbon, giving the 1,4-addition product: the nucleophile on the beta-carbon and the carbonyl restored.'],
    ],
    check: { q: 'What makes this a 1,4 (conjugate) addition rather than 1,2?', options: ['The nucleophile adds directly to the carbonyl carbon', 'The nucleophile adds to the beta-carbon and the charge ends up on oxygen', 'Two nucleophiles add at once'], answer: 1, explanation: 'In conjugate addition the nucleophile bonds to the beta-carbon and electrons relay through the conjugated system onto oxygen (the enolate), a 1,4 relationship.' },
    guidedViews: [
      { progress: .05, part: 'Nucleophile' },
      { progress: .4, part: 'Electrophile' },
      { progress: .6, part: 'Transition state' },
      { progress: .95, part: 'Transition state' },
    ],
    observationPrompts: [
      'Identify the beta-carbon (labelled) before the nucleophile arrives.',
      'Watch the nucleophile bond to the beta-carbon, not the carbonyl.',
      'Follow the electrons relaying through the conjugated system to oxygen.',
      'See the proton cap the alpha-carbon to give the 1,4-product.',
    ],
    readout: (p) => [
      ['Reaction type', '1,4-conjugate addition'],
      ['Nu adds to', 'beta-carbon (far from O)'],
      ['Intermediate', p < .5 ? 'enone' : p < .78 ? 'enolate' : 'protonated'],
      ['Product', p < .6 ? 'not yet' : '1,4-addition product'],
    ],
    playMs: 6400,
  },
];
