export const mechanismSpecs = [
  {
    id: 'sn2',
    label: 'SN2',
    title: 'SN2 substitution',
    short: 'Backside attack and inversion',
    question: 'How can one elementary step form a bond, break a bond, and invert a stereocentre?',
    summary: 'Scrub through a hydroxide SN2 substitution and connect electron movement, geometry, and activation energy.',
    evidence: 'Idealized SN2 reaction coordinate - geometry and energy are teaching models, not a quantum calculation.',
    control: ['Reactants', 'Products'],
    legend: ['electron pair', 'forming C-O bond', 'breaking C-Cl bond', 'single energy barrier'],
    swatches: ['#e0ad35', '#69736f', '#67a85f', '#a57a31'],
    parts: {
      Nucleophile: 'An electron-pair donor that approaches the carbon from the side opposite the leaving group.',
      Electrophile: 'The carbon atom accepting an electron pair as the new bond forms.',
      'Leaving group': 'The atom or group departing with the shared electron pair from the breaking bond.',
      'Transition state': 'A fleeting maximum-energy arrangement with partial bonds to both incoming and leaving groups.',
    },
    steps: [
      ['Backside approach', 'The nucleophile approaches opposite the leaving group, aligning its electron pair with the C-X antibonding orbital.'],
      ['One concerted event', 'Bond formation and bond breaking occur together. There is no stable intermediate in an elementary SN2 step.'],
      ['The energy barrier', 'The transition state is less stable than reactants or products, producing the activation-energy maximum.'],
      ['Configuration inverts', 'The three substituents turn through the carbon centre like an umbrella, giving inversion of stereochemistry.'],
    ],
    check: { q: 'At the energy maximum, what must the bond display show?', options: ['Only a complete C-O bond', 'A stable carbocation between two separate steps', 'Partial C-O formation and partial C-Cl cleavage at the same time'], answer: 2, explanation: 'The synchronized midpoint shows the concerted transition state rather than a stable intermediate.' },
    guidedViews: [
      { progress: .05, part: 'Nucleophile' },
      { progress: .48, part: 'Transition state' },
      { progress: .5, part: 'Transition state' },
      { progress: .92, part: 'Leaving group' },
    ],
    observationPrompts: [
      'Check the nucleophile and leaving group before scrubbing.',
      'Pause near the maximum and inspect both curved electron arrows.',
      'Compare the partial bonds with the energy marker.',
      'Follow H, D and CH3 as the tetrahedral center inverts.',
    ],
    playMs: 4200,
  },
  {
    id: 'suzuki',
    label: 'Suzuki',
    title: 'Suzuki C-C coupling',
    short: 'Pd carries two aryl groups',
    question: 'How can a palladium catalyst connect two carbon fragments without being consumed?',
    summary: 'Follow an idealized Suzuki-Miyaura sequence from aryl bromide and arylboronic acid through an oblique Pd(II) square plane to a twisted biaryl product.',
    evidence: 'Idealized Pd catalytic sequence - oxidative addition, aryl transfer, and reductive elimination are shown as formal teaching states. The Pd(II) square plane and aryl torsions are geometric teaching guides, not a calculated electronic structure. Ligand identity, active Pd species, and rate-limiting step depend on conditions.',
    control: ['Reactants', 'Biaryl product'],
    legend: ['aromatic aryl ring', 'Pd catalyst', 'square-planar Pd(II) guide', 'forming C-C bond'],
    swatches: ['#45504d', '#b9c0bf', '#8aa5a8', '#d4ae45'],
    parts: {
      'Aryl bromide': 'One carbon fragment enters the cycle through a C-Br bond. The display uses a generic aryl bromide rather than claiming one substrate or ligand set.',
      'Arylboronic acid': 'The second aryl fragment starts as Ar-B(OH)2. Base activation and the detailed boronate exchange network are condensed into the aryl-transfer teaching state.',
      'Palladium catalyst': 'Palladium changes coordination and formal oxidation state through the cycle. Formal Pd(0)/Pd(II) labels are bookkeeping, not literal point charges on the atom.',
      'cis-diaryl Pd': 'A teaching representation of the Pd(II) intermediate after aryl transfer. The four donors occupy one square plane, while the aryl ring planes are torsioned about their Pd-C bonds so they can be inspected separately.',
      'Biaryl product': 'The new C-C bond joins the two aryl fragments. The rings are drawn twisted about that bond, not as an artificially flat biphenyl. Palladium is regenerated and is not part of the product.',
    },
    steps: [
      ['Start with both aryl partners', 'The generic aryl bromide and arylboronic acid are shown alongside a formal Pd(0) catalyst state. The next step opens the C-Br bond rather than making a direct C-C jump.'],
      ['Oxidative addition opens C-Br', 'A Pd centre interacts with the aryl C-Br bond. The model condenses ligand details into an idealized formal oxidative-addition state with Pd-C and Pd-Br bonds in an oblique square plane.'],
      ['Aryl transfer builds cis-diaryl Pd', 'A base-activated boronate can transfer its aryl fragment to palladium. Inspect the two cis Pd-C bonds, the two L donors, and the distinct torsion of each aryl ring about its Pd-C bond.'],
      ['Reductive elimination makes C-C', 'The C-C bond forms as the biaryl product leaves with a visible ring twist, while a formal Pd(0) catalyst state is regenerated. The catalyst mediates the pathway but is not consumed.'],
    ],
    check: { q: 'Which observation identifies palladium as a catalyst in this teaching cycle?', options: ['Bromine remains attached to the aryl product', 'A Pd-bound intermediate gives a biaryl product and a regenerated Pd state', 'The two aryl rings begin on opposite sides of the view'], answer: 1, explanation: 'The display follows the carbon fragments into the biaryl product while palladium returns to a state available for another cycle.' },
    guidedViews: [
      { progress: .04, part: 'Aryl bromide' },
      { progress: .36, part: 'Palladium catalyst' },
      { progress: .62, part: 'cis-diaryl Pd' },
      { progress: .96, part: 'Biaryl product' },
    ],
    observationPrompts: [
      'Locate the aryl C-Br and aryl-B bonds before palladium engages either fragment.',
      'Follow the C-Br bond as Pd-C and Pd-Br bonds appear.',
      'Inspect the two cis Pd-C bonds and the two L donors in the oblique square plane after bromide has left.',
      'Check that the biaryl leaves with a ring twist while the Pd centre returns as a separate catalyst state.',
    ],
    playMs: 7600,
  },
  {
    id: 'dielsAlder',
    label: '[4+2]',
    title: 'Diels-Alder [4+2]',
    short: 'Orbital phase makes a ring',
    question: 'Why can a diene and dienophile form two C-C bonds in one thermal step?',
    summary: 'Align butadiene and ethene, inspect a qualitative frontier-orbital phase model, then follow a concerted [4+2] cycloaddition to cyclohexene.',
    evidence: 'Idealized thermal Diels-Alder symmetry archetype - phase-coloured lobe coefficients are a qualitative LCAO model, not calculated electron trajectories, charge clouds, or molecular-orbital isosurfaces. Unactivated butadiene plus ethene is shown for symmetry, not as a routine room-temperature reaction.',
    control: ['Separated pi systems', 'Cyclohexene product'],
    legend: ['diene pi system', 'dienophile pi system', 'wavefunction phase', 'forming C-C sigma bonds'],
    swatches: ['#45504d', '#69736f', 'linear-gradient(90deg, #d37742 0 50%, #456ba4 50% 100%)', '#d4ae45'],
    parts: {
      'Diene HOMO': 'Qualitative phase-coloured p-lobes trace the pi framework of the s-cis diene. The terminal faces that meet the dienophile are enlarged, but the model is not a calculated orbital surface.',
      'Dienophile LUMO': 'Qualitative phase-coloured p-lobes represent ethene pi-star. Matching phase at both approaching terminal contacts allows constructive overlap in this thermal [4+2] teaching case.',
      'Transition state': 'A concerted cyclic arrangement with two partial C-C bonds. This model has no carbocation or zwitterionic intermediate.',
      Cycloadduct: 'Cyclohexene formed after two new sigma bonds appear and the pi bonds reorganize. Stereochemical outcomes depend on the starting geometry.',
    },
    steps: [
      ['Set the reactive diene geometry', 'Butadiene must adopt an s-cis arrangement that brings its terminal carbons to the same face of the dienophile.'],
      ['Match HOMO and LUMO phase', 'The phase-coloured terminal lobes show a qualitative constructive overlap at both forming contacts. Colour marks wavefunction sign, not charge.'],
      ['Cross one concerted barrier', 'Two C-C sigma bonds form in the same pericyclic event while the pi system reorganizes. Bond formation can be asynchronous in real substituted cases, but there is no ionic intermediate in this idealized pathway.'],
      ['Read the cyclohexene product', 'The product contains a new six-membered ring and one remaining pi bond. Concerted Diels-Alder reactions can be stereospecific; this unsubstituted model does not encode a particular stereochemical outcome.'],
    ],
    check: { q: 'What should the transition-state display show for this idealized thermal Diels-Alder reaction?', options: ['A carbocation after only one new C-C bond', 'Two partial C-C bonds in one cyclic arrangement', 'A complete product ring before the dienophile approaches'], answer: 1, explanation: 'The [4+2] display represents one concerted pericyclic step: both new sigma bonds are forming as the pi system reorganizes.' },
    guidedViews: [
      { progress: .26, part: 'Diene HOMO' },
      { progress: .42, part: 'Dienophile LUMO' },
      { progress: .65, part: 'Transition state' },
      { progress: .96, part: 'Cycloadduct' },
    ],
    observationPrompts: [
      'Find the two terminal diene carbons that will make the new sigma bonds.',
      'Compare the orange and blue terminal lobes across both approaching contacts.',
      'Pause in the cyclic transition arrangement and count two partial C-C bonds.',
      'Trace the same six carbon atoms into the cyclohexene ring and its remaining pi bond.',
    ],
    playMs: 5600,
  },
];
